### PR TITLE
Added an exit function

### PR DESCRIPTION
**Pull request by andyhmltn**
I've added an exit function to the client. It's well needed and kind of expected for an CLI.

### CODE REVIEW

**Comment by sysr-q** [comment]
This is included in my `devel-restructure` branch, so we'll leave it up to @Max00355 to see if he wants to include it here.

**Comment by f-prime** [comment]
Your branch does not include the total_coins command.

**Comment by sysr-q** [comment]
That was forked off pre-total_commands, but it wouldn't be hard to add in.

**Comment by andyhmltn** [comment]
Gunna close this as I'm fed up with seeing this in my PRs inbox and I'm pretty sure this PR isn't ever going to be responded to...

**Pull request closed without merging**
